AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance Template"

Parameters:
  Environment:
    Type: String
    Description: The environment name (e.g., development, production)
    AllowedValues:
      - development
      - production
      - default

  InstanceType:
    Type: String
    Description: The instance type to be provisioned
    Default: "t2.micro"

  ImageID:
    Type: String
    Description: The AMI for the EC2 instance
    Default: "ami-07c5ecd8498c59db5"
  
  SubnetId:
    Type: String
    Description: "Subnet ID from the VPC Template"

  VPCId:
    Type: String
    Description: "VPC ID from the VPC template"
  
  VPCCIDR:
    Type: String
    Description: "The Cidr Range of the VPC"

  PolicyName:
    Type: String
    Description: "Name for the IAM Role"
    Default: "SSMPolicy"

  ProfileName:
    Type: String
    Description: "Name for the IAM policy to be attached to the EC2 instance"
    Default: "S2S-EC2-SSMProfile"
  
  SSMRoleName:
    Type: String
    Description: "Name of the SSM Role name to be created"
    Default: "S2S_SSM_Role"

  EC2SGName:
    Type: String
    Description: "Name of the security group attached to the EC2 instance."
    Default: 'S2SEC2SG'

Resources:
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SSMRoleName}_${Environment}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"
    DeletionPolicy: Retain

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProfileName}-${Environment}'
      Path: "/"
      Roles:
        - !Ref SSMRole
    DependsOn: SSMRole

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for EC2 instances"
      VpcId: !Ref VPCId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VPCCIDR
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 98.247.36.44
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 98.247.36.44
      Tags:
        - Key: Name
          Value: !Sub '${EC2SGName}_${Environment}'

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageID
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: false
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub 'EC2_${Environment}'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
    DependsOn: 
      - SSMInstanceProfile
      - EC2SecurityGroup

Outputs:
  InstanceId:
    Description: "ID of the created EC2 instance"
    Value: !Ref EC2Instance