AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance Template"

Parameters:
  Environment:
    Type: String
    Description: The environment name (e.g., development, production)
    AllowedValues:
      - development
      - production
      - default

  InstanceType:
    Type: String
    Description: The instance type to be provisioned
    Default: "t2.micro"

  ImageID:
    Type: String
    Description: The AMI for the EC2 instance
    Default: "ami-07c5ecd8498c59db5"
  
  SubnetId:
    Type: String
    Description: "Subnet ID from the VPC Template"

  VPCId:
    Type: String
    Description: "VPC ID from the VPC template"

  PolicyName:
    Type: String
    Description: "Name for the IAM Role"
    Default: "SSMPolicy"

  ProfileName:
    Type: String
    Description: "Name for the IAM policy to be attached to the EC2 instance"
    Default: "SSMInstanceProfile"
  
  SSMRoleName:
    Type: String
    Description: "Name of the SSM Role name to be created"
    Default: "S2S_SSM_Role"

Resources:
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SSMRoleName}_${Environment}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"
    DeletionPolicy: Retain

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProfileName}_${Environment}'
      Path: "/"
      Roles:
        - !Ref SSMRole
    DependsOn: SSMRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageID
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: false
          SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub 'EC2_${Environment}'
    DependsOn: 
      - SSMInstanceProfile

Outputs:
  InstanceId:
    Description: "ID of the created EC2 instance"
    Value: !Ref EC2Instance